n= set()
a= input("Enter the number: ")
n.add(int(a))
a= input("Enter the number: ")
n.add(int(a))
a= input("Enter the number: ")
n.add(int(a))
a= input("Enter the number: ")
n.add(int(a))
a= input("Enter the number: ")
n.add(int(a))
a= input("Enter the number: ")
n.add(int(a))
a= input("Enter the number: ")
n.add(int(a))
a= input("Enter the number: ")
n.add(int(a))
print(n)

