marks= []
marks0= input("Enter marks of student 1: ")
marks.append(marks0)
marks1= input("Enter marks of student 2: ")
marks.append(marks1)
marks2= input("Enter marks of student 3: ") 
marks.append(marks2)
marks3= input("Enter marks of student 4: ")
marks.append(marks3)
marks4= input("Enter marks of student 5: ")
marks.append(marks4)
marks5= input("Enter marks of student 6: ")
marks.append(marks5)
print(marks)
marks.sort()